import { ArrowCounterClockwise, CaretDown, CheckCircle, MapPin, PencilSimple, Plus, Trash, WarningCircle } from '@phosphor-icons/react'
import { useState } from 'react'
import { rooms as fallbackRooms } from '../../data/mocks'
import { EmptyState } from '../../components/ui/EmptyState'
import { Toolbar } from '../../components/ui/Toolbar'
import type { Assignment, Campus, Room, Screen } from '../../types/domain'
import { findAssignmentConflicts } from './conflicts'

type PlanningViewProps = { screen: Screen; query: string; setQuery: (value: string) => void; onCreate: () => void; onCreateCampus?: () => void; onNotify: (value: string) => void; rooms?: Room[]; campuses?: Campus[]; assignments?: Assignment[]; onEditRoom?: (id: number) => void; onDeactivateRoom?: (id: number) => void; onRestoreRoom?: (id: number) => void; onEditAssignment?: (id: number) => void; onDeactivateAssignment?: (id: number) => void }

export function PlanningView({ screen, query, setQuery, onCreate, onCreateCampus, onNotify, rooms = fallbackRooms, campuses, assignments = [], onEditRoom, onDeactivateRoom, onRestoreRoom, onEditAssignment, onDeactivateAssignment }: PlanningViewProps) {
  const [roomStatus, setRoomStatus] = useState('')
  if (screen === 'Agenda') return <Agenda assignments={assignments} onNotify={onNotify} />
  if (screen === 'Asignaciones') return <Assignments assignments={assignments} onNotify={onNotify} onCreate={onCreate} onEdit={onEditAssignment} onDeactivate={onDeactivateAssignment} />

  const rows = rooms.filter((room) => `${room.name} ${room.campus} ${room.type}`.toLowerCase().includes(query.toLowerCase()) && (!roomStatus || room.status === roomStatus))
  return <><Toolbar query={query} setQuery={setQuery} placeholder="Buscar sede o aula..." filterValue={roomStatus} onFilterChange={setRoomStatus} filterOptions={['Disponible', 'En uso', 'Inactiva']} action={<span className="toolbar-actions"><button className="secondary-button" onClick={onCreateCampus}><Plus size={17} /> Nueva sede</button><button className="primary-button" onClick={onCreate}><Plus size={17} /> Nueva aula</button></span>} /><div className="section-title"><span><h2>Sedes</h2></span></div><div className="campus-strip">{(campuses ?? [{ id: 1, name: 'Monserrat', roomsCount: 18 }, { id: 2, name: 'Recoleta', roomsCount: 9 }, { id: 3, name: 'Pilar', roomsCount: 7 }]).map((campus) => <span key={campus.id}><MapPin size={18} /> {campus.name} <b>{campus.roomsCount} aulas</b></span>)}</div><div className="section-title"><span><h2>Aulas</h2></span></div><div className="table-wrap"><table><thead><tr><th>Aula</th><th>Sede</th><th>Tipo</th><th>Capacidad</th><th>Estado</th><th aria-label="Acciones" /></tr></thead><tbody>{rows.map((room) => <tr key={room.id}><td><strong>{room.name}</strong></td><td>{room.campus}</td><td>{room.type}</td><td>{room.capacity} personas</td><td><span className={`status ${room.status === 'Disponible' ? 'success' : 'warning'}`}><i />{room.status}</span></td><td><button className="row-action" onClick={() => onEditRoom ? onEditRoom(room.id) : onNotify(`Editando ${room.name}`)} aria-label={`Editar ${room.name}`}><PencilSimple size={17} /></button>{room.status !== 'En uso' && room.status !== 'Inactiva' && onDeactivateRoom && <button className="row-action danger" onClick={() => onDeactivateRoom(room.id)} aria-label={`Desactivar ${room.name}`}><Trash size={17} /></button>}{room.status === 'Inactiva' && onRestoreRoom && <button className="row-action" onClick={() => onRestoreRoom(room.id)} aria-label={`Restaurar ${room.name}`}><ArrowCounterClockwise size={17} /></button>}</td></tr>)}</tbody></table>{rows.length === 0 && <EmptyState query={query} />}</div></>
}

function Assignments({ assignments, onNotify, onCreate, onEdit, onDeactivate }: { assignments: Assignment[]; onNotify: (value: string) => void; onCreate: () => void; onEdit?: (id: number) => void; onDeactivate?: (id: number) => void }) {
  const conflicts = findAssignmentConflicts(assignments)
  const slots = assignments.length ? assignments : [{ id: 0, time: '', course: '', room: '', day: '', start: '08:00', end: '10:00', period: '' }]
  return <><div className="assignment-toolbar"><div className="select-like">2.º cuatrimestre 2026 <CaretDown size={15} /></div><div className="select-like">Semana del 17 jun <CaretDown size={15} /></div><button className="secondary-button" onClick={() => onNotify(conflicts.length ? `Se detectaron ${conflicts.length} superposiciones.` : 'Conflictos revisados: no se encontraron superposiciones')}><CheckCircle size={16} /> Revisar conflictos</button><button className="primary-button" onClick={onCreate}><Plus size={17} /> Nueva asignación</button></div>{conflicts.length > 0 && <div className="inline-warning" role="alert"><WarningCircle size={19} weight="fill" /><span><strong>Hay {conflicts.length} superposición{conflicts.length > 1 ? 'es' : ''} de horario.</strong> Revisá las aulas y franjas involucradas.</span></div>}<div className="schedule"><div className="schedule-head"><span>HORARIO</span><span>LUNES</span><span>MARTES</span><span>MIÉRCOLES</span><span>JUEVES</span><span>VIERNES</span></div>{slots.map((slot) => <div className="schedule-row" key={slot.id}><span>{slot.start}{slot.end ? ` - ${slot.end}` : ''}</span>{['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'].map((day) => <div className={slot.day === day ? `scheduled ${day === 'Martes' ? 'green-card' : day === 'Miércoles' ? 'purple-card' : ''}` : ''} key={day}>{slot.day === day && <><strong>{slot.course}</strong><small>{slot.room}</small></>}</div>)}</div>)}</div><div className="assignment-list">{assignments.map((assignment) => <div className="assignment-item" key={assignment.id}><span><strong>{assignment.course}</strong><small>{assignment.day} · {assignment.start}–{assignment.end} · {assignment.room}</small></span><span><button className="row-action" onClick={() => onEdit?.(assignment.id)} aria-label={`Editar asignación de ${assignment.course}`}><PencilSimple size={17} /></button><button className="row-action danger" onClick={() => onDeactivate?.(assignment.id)} aria-label={`Desactivar asignación de ${assignment.course}`}><Trash size={17} /></button></span></div>)}</div><div className="legend"><span><i className="blue-dot" /> Cursos asignados</span><span><i className="green-dot" /> Disponible</span><span><i className="red-dot" /> Superposición detectada</span></div></>
}

function Agenda({ assignments, onNotify }: { assignments: Assignment[]; onNotify: (value: string) => void }) {
  const days = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes']
  return <><div className="agenda-toolbar"><button className="calendar-nav" onClick={() => onNotify('Semana anterior')} aria-label="Semana anterior">‹</button><strong>17 - 23 de junio, 2026</strong><button className="calendar-nav" onClick={() => onNotify('Semana siguiente')} aria-label="Semana siguiente">›</button><button className="secondary-button today" onClick={() => onNotify('Volviste a hoy')}>Hoy</button></div><div className="agenda-grid">{days.map((day, index) => { const events = assignments.filter((assignment) => assignment.day === day); return <div className="agenda-day" key={day}><strong>{day} {17 + index}</strong><span className="agenda-count">{events.length} reservas</span>{events.map((assignment, item) => <div className={`agenda-event event-${(index + item) % 3}`} key={assignment.id}><small>{assignment.start}</small><strong>{assignment.course}</strong><span>{assignment.room}</span></div>)}</div> })}</div></>
}
